version: '2'
services:

  web:
    build: .
    volumes:
      - ./src:/app'
    ports:
      - "80:80"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/election"

  mongo:
    image: mongo:3
    command: mongod --smallfiles
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
    networks:
      - all

  mongodata:
    image: tianon/true
    volumes:
      - /data/mongo

networks:
  all: