version: '2'
services:

  app:
    build: .
    volumes:
      - ./src:/src'
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - all
    environment:
      NODE_ENV: "dev"

  mongodb:
    image: mongo:3.4.0
    command: mongod --smallfiles
    volumes_from:
      - mongodb-data
    ports:
      - "27017:27017"
    networks:
      - all

  mongodb-data:
    image: tianon/true
    volumes:
      - ./src/mongodb/data:/data

networks:
  all:
